[package]
name = "monte_carlo_pi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy-inspector-egui = "0.17.0"
bevy_rapier3d = "0.20.0"
rand = "0.8.5"
